name: Deploy to Hostinger VPS

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Copy files to VPS via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTINGER_SERVER }}
        username: ${{ secrets.HOSTINGER_USER }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "dist/*"
        target: "${{ secrets.HOSTINGER_TARGET_DIR }}"
        strip_components: 1

    - name: Confirm success
      run: echo "✅ Deployment done!"
